# Generated by Django 5.2.3 on 2025-06-14 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('section', models.CharField(max_length=50)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64)),
                ('age', models.CharField(choices=[('0–2', '0–2 (Infant)'), ('3–12', '3–12 (Child)'), ('13–17', '13–17 (Teen)'), ('18–24', '18–24 (Young Adult)'), ('25–34', '25–34 (Early Adult)'), ('35–44', '35–44 (Middle Adult)'), ('45–54', '45–54 (Older Adult)'), ('55–64', '55–64 (Senior)'), ('65+', '65+ (Elder)')], max_length=16)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('total_score', models.FloatField()),
                ('scores', models.JSONField()),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.questionnaire')),
            ],
        ),
    ]
