# Generated by Django 5.2.3 on 2025-06-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[('short_text', 'Short Text'), ('long_text', 'Long Text'), ('select', 'Select'), ('checkbox_multiple', 'Checkboxes'), ('number', 'Number')], default='short_text', max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
