# Generated by Django 5.2.3 on 2025-06-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_question_input_type_alter_question_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('years', models.CharField(max_length=10)),
                ('primary_language', models.CharField(blank=True, max_length=100)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('other_language', models.CharField(blank=True, max_length=100)),
                ('algorithms', models.CharField(max_length=50)),
                ('data_structures', models.CharField(max_length=50)),
                ('challenges', models.CharField(max_length=50)),
                ('git', models.CharField(max_length=50)),
                ('ci_cd', models.CharField(max_length=50)),
                ('testing', models.CharField(max_length=50)),
                ('open_source', models.CharField(max_length=50)),
                ('largest_project', models.TextField(blank=True)),
                ('agile', models.CharField(max_length=50)),
                ('architecture', models.CharField(max_length=50)),
                ('concepts', models.CharField(max_length=50)),
                ('deployment', models.CharField(max_length=50)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('platform_other', models.CharField(blank=True, max_length=100)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('interests_other', models.CharField(blank=True, max_length=100)),
                ('learning', models.CharField(max_length=50)),
            ],
        ),
    ]
