# Generated by Django 5.2.3 on 2025-06-21 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_survey_slug'),
    ]

    operations = [
            migrations.RemoveField(
                model_name='section',
                name='label',
            ),
        ]
