# Generated by Django 5.2.3 on 2025-06-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20250621_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
